package com.main.objects;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.mongodb.BasicDBList;
import com.mongodb.DBObject;

import org.bson.Document;
import org.bson.types.ObjectId;

public class Hotel {
    
    public static enum RoomType {STANDARD, QUEEN, KING};

    private String name = "Hotel Name";
    private String description = "";
    
    // Amount of Available rooms for each type
    private int standardRooms = 0;
    private int queenRooms = 0;
    private int kingRooms = 0;

    // Standard rooms have standard amenities, queen rooms have all standard amenities plus the queen amenities, 
    // and finally king rooms have all queen amenities plus king amenities.
    private List<Amenity> standardAmenities = null;
    private List<Amenity> queenAmenities = null;
    private List<Amenity> kingAmenities = null;

    // Pricing for each room type.
    private float roomPriceStandard = 100.00f;
    private float roomPriceQueen = 150.00f;
    private float roomPriceKing = 250.00f;

    // The additive multiplyer added to room prices for the weekends.
    private float weekendDifferential = .25f;

    private ObjectId ID; // Unique ID generated by MongoDB, this value is set when the object is retrieved from the Database.

    // The Total amount of rooms available, Useful for sorting hotels by rooms available
    public int getTotalRooms(){
        return kingRooms + queenRooms + standardRooms;
    }

    public List<Amenity> getStandardAmenities() {
        return standardAmenities;
    }

    public List<Amenity> getKingAmenities() {
        return kingAmenities;
    }

    public List<Amenity> getQueenAmenities() {
        return queenAmenities;
    }
    
    public int getKingRooms() {
        return kingRooms;
    }
    
    public int getQueenRooms() {
        return queenRooms;
    }
    
    public int getStandardRooms() {
        return standardRooms;
    }
    
    public ObjectId getID() {
        return ID;
    }
    
    public float getWeekendDifferential() {
        return weekendDifferential;
    }
    
    public float getRoomPriceKing() {
        return roomPriceKing;
    }
    
    public float getRoomPriceQueen() {
        return roomPriceQueen;
    }
    
    public float getRoomPriceStandard() {
        return roomPriceStandard;
    }
    public String getDescription() {
        return description;
    }
    
    public String getName() {
        return name;
    }
    
    public void setKingAmenities(List<Amenity> kingAmenities) {
        this.kingAmenities = kingAmenities;
    }

    public void setQueenAmenities(List<Amenity> queenAmenities) {
        this.queenAmenities = queenAmenities;
    }

    public void setKingRooms(int kingRooms) {
        this.kingRooms = kingRooms;
    }

    public void setQueenRooms(int queenRooms) {
        this.queenRooms = queenRooms;
    }

    public void setStandardRooms(int standardRooms) {
        this.standardRooms = standardRooms;
    }

    public void setID(ObjectId iD) {
        this.ID = iD;
    }

    public void setWeekendDifferential(float weekendDifferential) {
        this.weekendDifferential = weekendDifferential;
    }

    public void setRoomPriceKing(float roomPriceKing) {
        this.roomPriceKing = roomPriceKing;
    }

    public void setRoomPriceQueen(float roomPriceQueen) {
        this.roomPriceQueen = roomPriceQueen;
    }

    public void setRoomPriceStandard(float roomPriceStandard) {
        this.roomPriceStandard = roomPriceStandard;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setStandardAmenities(List<Amenity> amenities) {
        this.standardAmenities = amenities;
    }

    // Convert this Hotel into a Document to be stored in the Database
    public Document ToDocument(){

        Document document = new Document();

        document.append("Name", this.name);
        document.append("Description", this.description);

        document.append("Standard Rooms", this.standardRooms);
        document.append("Queen Rooms", this.queenRooms);
        document.append("King Rooms", this.kingRooms);

        List<Document> saDoc = new ArrayList<>();
        List<Document> qDoc = new ArrayList<>();
        List<Document> kDoc = new ArrayList<>();

        if(standardAmenities != null)
            for(Amenity amenity : standardAmenities)
                saDoc.add(amenity.ToDocument());

        if(queenAmenities != null)
            for(Amenity amenity : queenAmenities)
                qDoc.add(amenity.ToDocument());

        if(kingAmenities != null)
            for(Amenity amenity : kingAmenities)
                kDoc.add(amenity.ToDocument());

        document.append("Standard Amenities", saDoc);
        document.append("Queen Amenities", qDoc);
        document.append("King Amenities", kDoc);

        document.append("RoomPriceStandard", this.roomPriceStandard);
        document.append("RoomPriceQueen", this.roomPriceQueen);
        document.append("RoomPriceKing", this.roomPriceKing);

        document.append("WeekendDifferential", this.weekendDifferential);

        return document;

    }

    // Convert given Document into a Hotel Object.
    public static Hotel ToHotel(Document document){

        Hotel hotel = new Hotel();

        hotel.name = (String) document.get("Name");
        hotel.description = (String) document.get("Description");

        hotel.standardRooms = (int) document.get("Standard Rooms");
        hotel.queenRooms = (int) document.get("Queen Rooms");
        hotel.kingRooms = (int) document.get("King Rooms");

        hotel.standardAmenities = Arrays.asList((Amenity[]) document.get("Standard Amenities"));
        hotel.queenAmenities = Arrays.asList((Amenity[]) document.get("Queen Amenities"));
        hotel.kingAmenities = Arrays.asList((Amenity[]) document.get("King Amenities"));

        hotel.roomPriceStandard = (float) document.get("RoomPriceStandard");
        hotel.roomPriceQueen = (float) document.get("RoomPriceQueen");
        hotel.roomPriceKing = (float) document.get("RoomPriceKing");

        hotel.weekendDifferential = (float) document.get("WeekendDifferential");

        hotel.ID = (ObjectId) document.get("_id");

        return hotel;

    }
}
